// Extracts the icons BasinWright actually uses from @fluentui/svg-icons into a
// single generated module of raw path data.
//
// Why not import @fluentui/react-icons directly: those components are built on
// Griffel (runtime CSS-in-JS) and React hooks, which would force a client
// boundary on every server-rendered section that shows an icon, and ship a
// second styling runtime alongside Tailwind. Raw paths cost nothing.
//
// Run with: node scripts/generate-icons.mjs

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const ICON_DIR = "node_modules/@fluentui/svg-icons/icons";
const OUT = "src/components/fluent-icons.generated.ts";
const SIZE = 24;

/// Semantic name -> candidate Fluent basenames, in preference order.
const MAP = {
  // Platform & product
  Activity: ["pulse"],
  AudioLines: ["sound_wave_circle", "mic"],
  Bot: ["bot"],
  Boxes: ["cube_multiple", "cube"],
  Building2: ["building_multiple", "building"],
  Cloud: ["cloud"],
  CloudCog: ["cloud_settings", "cloud_sync"],
  Cloudy: ["cloud_arrow_up", "cloud"],
  Code2: ["code"],
  Cpu: ["developer_board", "chip"],
  Database: ["database"],
  Factory: ["building_factory"],
  FileText: ["document_text", "document"],
  Fuel: ["gas_pump", "drop"],
  Gavel: ["gavel"],
  Globe: ["globe"],
  GraduationCap: ["hat_graduation"],
  HeartPulse: ["heart_pulse"],
  Headset: ["headset"],
  Landmark: ["building_bank"],
  Layers: ["layer_diagonal", "layer"],
  LayoutDashboard: ["board", "grid"],
  Library: ["library", "book"],
  LineChart: ["data_trending", "data_line"],
  Lock: ["lock_closed"],
  MessageSquare: ["chat"],
  Microscope: ["beaker"],
  Network: ["share_android", "organization"],
  Radio: ["broad_activity_feed", "access_time"],
  RadioTower: ["cellular_5g", "cellular_data_1"],
  Rocket: ["rocket"],
  Scale: ["scales"],
  Search: ["search"],
  Server: ["server"],
  Shapes: ["shapes"],
  Shield: ["shield"],
  ShieldAlert: ["shield_error", "shield_prohibited"],
  ShieldCheck: ["shield_checkmark", "shield_task"],
  ShoppingBag: ["shopping_bag"],
  ShoppingCart: ["cart"],
  SlidersHorizontal: ["options"],
  Sparkles: ["sparkle"],
  Store: ["building_retail", "building_shop"],
  Train: ["vehicle_subway"],
  TrendingUp: ["arrow_trending"],
  Truck: ["vehicle_truck_profile", "vehicle_truck"],
  Umbrella: ["umbrella"],
  Users: ["people"],
  Wrench: ["wrench"],
  Zap: ["flash"],
  Eye: ["eye"],

  // UI & admin chrome
  ArrowLeft: ["arrow_left"],
  ArrowRight: ["arrow_right"],
  ArrowUp: ["arrow_up"],
  ArrowDown: ["arrow_down"],
  ArrowUpRight: ["arrow_up_right"],
  Check: ["checkmark"],
  ChevronRight: ["chevron_right"],
  ChevronDown: ["chevron_down"],
  Circle: ["circle"],
  Dismiss: ["dismiss"],
  Menu: ["navigation"],
  EyeOff: ["eye_off"],
  Plus: ["add"],
  Trash: ["delete"],
  LogOut: ["sign_out"],
  ExternalLink: ["open"],
  Inbox: ["mail_inbox"],
  Settings: ["settings"],
  LayoutList: ["apps_list"],
  Spinner: ["arrow_clockwise", "arrow_sync"],
  Sun: ["weather_sunny"],
  Moon: ["weather_moon"],
  Desktop: ["desktop"],
};

/// Pulls the drawable children out of an SVG file and normalises colour so the
/// icon inherits `currentColor` from its container.
function extract(file) {
  const raw = readFileSync(file, "utf8");

  const viewBox = raw.match(/viewBox="([^"]+)"/)?.[1] ?? `0 0 ${SIZE} ${SIZE}`;
  const body = raw.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "");

  // Regular icons ship a hardcoded dark fill; drop it so currentColor wins.
  const normalised = body
    .replace(/\s*fill="#[0-9a-fA-F]{3,8}"/g, "")
    .replace(/\s*fill="none"/g, ' fill="none"')
    .trim();

  return { viewBox, body: normalised };
}

const entries = [];
const missing = [];

for (const [name, candidates] of Object.entries(MAP)) {
  let found = null;

  for (const base of candidates) {
    const file = join(ICON_DIR, `${base}_${SIZE}_regular.svg`);
    if (existsSync(file)) {
      found = { base, ...extract(file) };
      break;
    }
  }

  if (found) entries.push([name, found]);
  else missing.push(`${name} (tried ${candidates.join(", ")})`);
}

if (missing.length) {
  console.error("Unresolved icons:\n  " + missing.join("\n  "));
  process.exit(1);
}

const file = `// GENERATED by scripts/generate-icons.mjs — do not edit by hand.
// Source: Fluent System Icons (MIT) — https://github.com/microsoft/fluentui-system-icons
// Re-run after changing the map in that script.

export type FluentIconData = { viewBox: string; body: string };

export const FLUENT_ICONS = {
${entries
  .map(
    ([name, d]) =>
      `  ${name}: { viewBox: ${JSON.stringify(d.viewBox)}, body: ${JSON.stringify(d.body)} },`,
  )
  .join("\n")}
} as const satisfies Record<string, FluentIconData>;

export type FluentIconName = keyof typeof FLUENT_ICONS;
`;

writeFileSync(OUT, file);

const bytes = Buffer.byteLength(file);
console.log(
  `Wrote ${entries.length} icons to ${OUT} (${(bytes / 1024).toFixed(1)} kB)`,
);
